config/routes.rb
Oneclick::Application.routes.draw do
  get '/configuration' => 'configuration#configuration'

  scope "(:locale)", locale: oneclick_available_locales do

    if Oneclick::Application.config.ui_mode == 'kiosk'
      root to: redirect('/kiosk')
    else
      root to: 'home#index'
    end

    authenticated :user do
      root :to => 'trips#new', as: :authenticated_root
    end

    devise_for :users, controllers: {registrations: "registrations", sessions: "sessions", passwords: 'passwords'}

    resources :content

    get "user_relationships/:id/check/" => "user_relationships#check_update", as: :check_update_user_relationship # need to support client-side logic with server-side vaildations
    # everything comes under a user id
    resources :users, except: [:index] do
      member do
        get   'find_by_email'
        get   'profile'
        post  'initial_booking'
        post  'add_booking_service'
        # post  'update'
        get   '/assist/:buddy_id', to: 'users#assist', as: :assist
      end

      resources :characteristics, :only => [:new, :create, :edit, :update] do
        collection do
          get 'header'
          post 'update'
        end
        member do
          put 'set'
        end
      end

      resources :sidewalk_obstructions, :only => [:create, :update] do
        collection do
          post "approve"
          post "reject"
          post "delete"
        end
      end

      resources :programs, :only => [:new, :create, :edit, :update] do
        member do
          put 'set'
        end
      end

      resources :accommodations, :only => [:new, :create, :edit, :update] do
        member do
          put 'set'
        end
      end

      resources :agency_user_relationships, controller: 'admin/agency_user_relationships', :only => [:create,:destroy] do
        member do
          get   'traveler_revoke'
          get   'traveler_hide'
        end
      end


      # user relationships
      resources :user_relationships, :only => [:new, :create] do
        member do
          get   'traveler_retract'
          get   'traveler_revoke'
          get   'traveler_hide'
          get   'delegate_accept'
          get   'delegate_decline'
          get   'delegate_revoke'
        end
      end

      # users have places
      resources :places, :only => [:index, :new, :create, :destroy, :edit, :update] do
        collection do
          post 'handle'
          get   'search'
          post  'geocode'
        end
      end

      # users have trips
      resources :trips, :only => [:show, :index, :new, :create, :destroy, :edit, :update] do
        get 'multi_od_grid/:multi_od_trip_id' => 'trips#multi_od_grid', as: 'multi_od_grid'
        resources :characteristics, only: [:new, :update], controller: 'characteristics'
        collection do
          post  'set_traveler'
          get   'unset_traveler'
          get   'search'
          post  'geocode'
          get   'plan_map'
          get   'create_multi_od'
        end
        member do
          get   'populate'
          get   'repeat'
          get   'select'
          get   'details'
          get   'itinerary'
          post  'email'
          post  'email_provider'
          post  'email_itinerary'
          get   'email_itinerary2_values'
          post  'email2'
          get   'hide'
          get   'unhide_all'
          get   'skip'
          post  'comments'
          post  'admin_comments'
          get   'email_feedback'
          get   'show_printer_friendly'
          get   'example'
          get   'book'
          get   'plan'
          get   'new_rating_from_email'
          post  'cancel'
          get   'serialize_trip'
        end
        resources :itineraries do
          member do
            get 'map_status'
            get 'request_create_map'
            get 'create_map'
          end
        end
        resources :trip_parts do
          member do
            get 'reschedule'
          end
        end
      end

      resources :trip_parts do
        member do
          get 'itineraries'
          get 'unhide_all'
          get 'unselect_all'
        end
      end

      resources :user_services do
        member do
          post 'update'
        end
      end
    end
    # scope('/kiosk') do
    #   devise_for :users, as: 'kiosk', controllers: {sessions: "kiosk/sessions"}
    # end

    # get '/kiosk_user/kiosk/users/sign_in', to: 'kiosk/sessions#create'


    get 'place_details/:id' => 'place_searching#details', as: 'place_details'
    get 'reverse_geocode' => 'place_searching#reverse_geocode', as: 'reverse_geocode'

    namespace :kiosk do
      get '/', to: 'home#index'
      get 'reset', to: 'home#reset'

      get 'itineraries/:id/print' => 'trips#itinerary_print', as: 'print_itinerary'

      resources :locations, only: [:show]
      resources :call, only: [:show, :index] do
        post :outgoing, on: :collection
      end

      # TODO can probably remove a lot of these routes
      resources :users do
        member do
          get   'profile'
          post  'update'
        end

        namespace :new_trip do
          resource :start
          resource :to
          resource :from
          resource :pickup_time
          resource :purpose
          resource :return_time
          resource :overview
        end

        resources :characteristics, :only => [:new, :create, :edit, :update] do
          collection do
            get 'header'
          end
          member do
            put 'set'
          end
        end

        resources :programs, :only => [:new, :create, :edit, :update] do
          member do
            put 'set'
          end
        end

        resources :accommodations, :only => [:new, :create, :edit, :update] do
          member do
            put 'set'
          end
        end

        # user relationships
        resources :user_relationships, :only => [:new, :create] do
          member do
            get   'traveler_retract'
            get   'traveler_revoke'
            get   'traveler_hide'
            get   'delegate_accept'
            get   'delegate_decline'
            get   'delegate_revoke'
          end
        end

        # users have places
        resources :places, :only => [:index, :new, :create, :destroy, :edit, :update] do
          collection do
            get   'search'
            post  'geocode'
          end
        end

        # users have trips
        resources :trips, :only => [:show, :index, :new, :create, :destroy, :edit, :update] do
          collection do
            post  'set_traveler'
            get   'unset_traveler'
            get   'search'
            post  'geocode'
          end

          member do
            get 'start'
            get   'repeat'
            get   'select'
            get   'details'
            get   'itinerary'
            post  'email'
            post  'email_provider'
            post  'email_itinerary'
            get   'email_itinerary2_values'
            post  'email2'
            get   'hide'
            get   'unhide_all'
            get   'skip'
            post  'comments'
            post  'admin_comments'
            get   'email_feedback'
            get   'show_printer_friendly'
          end
        end

        resources :trip_parts do
          member do
            get 'unhide_all'
          end
        end

      end # kiosk

    end # user

    devise_scope :user do
      post '/kiosk/sign_in' => 'kiosk/sessions#create', as: :kiosk_user_session
      get '/kiosk/sign_in' => 'kiosk/sessions#new', as: :new_kiosk_user_session
      get '/kiosk/session/destroy' => 'kiosk/sessions#destroy', as: :destroy_kiosk_user_session
    end

    # TODO This should go somewhere else
    get '/place_search' => 'trips#search'
    get '/place_search_my' => 'trips#search_my'
    get '/place_search_poi' => 'trips#search_poi'
    get '/place_search_geo' => 'trips#search_geo'

    # reporting engine
    namespace :reporting do
      get '/'  => 'reports#index'
      resources :reports, only: [:index, :show] do
        resources :results, only: [:index]
      end
    end

    namespace :admin do

      get '/reports/trips_datatable' => 'reports#trips_datatable'

      resources :reports, :only => [:index, :show] do
        get 'results'
      end

      resources :trips, :only => [:index]
      resources :trip_parts, :only => [:index]
      get '/geocode' => 'util#geocode'
      get '/raise' => 'util#raise'
      get '/services' => 'util#services'
      get '/settings' => 'util#settings'
      patch '/load_pois' => 'pois#load_pois'
      get '/check_loading_status' => 'pois#check_loading_status'
      patch '/upload_application_logo' => 'util#upload_application_logo'
      patch '/upload_favicon' => 'util#upload_favicon'
      get '/' => 'admin_home#index'
      resource :feedback
      resources :sidewalk_obstructions, :only => [:index] do
        collection do
          patch "approve"
        end
      end
      resources 'agency_user_relationships' do
        get   'aid_user'
        get   'agency_revoke'
      end
      resources :agencies do
        get 'find_agent_by_email'
        get 'travelers'
        get "users/:id/agency_assist", to: "users#assist", as: :agency_assist
        resources 'agency_user_relationships' do
          get   'agency_revoke'
        end
        get 'select_user'
        member do
          patch 'undelete'
        end
        resources :trips
      end
      resources :users do
        get 'merge', on: :member, to: "users#merge_edit"
        patch 'merge', on: :member, to: "users#merge_submit"
        put 'update_roles', on: :member
        get 'find_by_email'
        member do
          patch 'undelete'
        end
      end
      resources :providers do
        get   'find_staff_by_email'
        resources :users
        resources :services
        resources :trips, only: [:index, :show]
        member do
          patch 'undelete'
        end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  include EligibilityOperators
  include EligibilityHelpers

  # attr_accessible :id, :code, :name, :note, :datatype, :active, :characteristic_type, :desc, :sequence

  has_many :user_characteristics
  has_many :user_profiles, through: :user_characteristics

  has_many :service_characteristics
  has_many :services, through: :service_characteristics

  belongs_to :linked_characteristic, class_name: 'Characteristic'

  # set the default scope
  default_scope {where('characteristics.active = ?', true)}
  scope :active, -> {where(active: true)}
  scope :personal_factors, -> {where('characteristic_type = ?', 'personal_factor')}
  scope :programs, -> {where('characteristic_type = ?', 'program')}
  scope :enabled, -> { where.not(datatype: 'disabled') }
  scope :for_traveler, -> { where(for_traveler: true) }
  scope :for_service, -> { where(for_service: true) }

  # return name value pairs suitable for passing to simple_form collection
  def self.form_collection include_all=true
    if include_all
      list = [[I18n.t(:all), -1]]
    else
      list = []
    end
    enabled.where(datatype: 'bool').order(name: :asc).each do |c|
      list << [I18n.t(c.name), c.id]
    end
    list
  end

  # builds a hash of details about a characteristic; is used by the javascript
  # client to knwo whether to ask the user for more info
  def for_missing_info(service, group, code)
    age = ''
    a = attributes
    sc = service_characteristics.where(service: service).take
    #value = case code
    #when 'age'
    #  Date.today.year - sc.value.to_i
    #else
    #  sc.value
    #end
    value = sc.value

    operator = case code
    when 'age'
      reverse_relationship_to_symbol(sc.rel_code)
    else
      relationship_to_symbol(sc.rel_code)
    end
    success_condition = "#{operator}#{value}"
    if code == 'age'
      a['datatype'] = 'bool'
      age = sc.value.to_s
      a['note'] = :ask_age
      success_condition = '== true'
    end

    options = a['datatype']=='bool' ? [{text: I18n.t(:yes_str), value: true}, {text: I18n.t(:no_str), value: false}] : nil
    {
      'question' => I18n.t(a['note'], age: age),
      #'description' => I18n.t(a['desc']),
      'data_type' => a['datatype'],
      # 'control_type' => '',
      'options' => options,
      'success_condition' => success_condition,
      'group_id' => group,
      'code' => code,
      'year' => value
    }
  end

end

app/controllers/api/v1/characteristics_controller.rb
module Api
  module V1
    class CharacteristicsController < Api::V1::ApiController

      def index
        characteristics = Characteristic.where(active: true)

        characteristics_questions = []
        characteristics.each do |characteristic|
          note = I18n.t(characteristic.note)
          code = characteristic.code
          type = characteristic.datatype
          characteristics_questions.append({text: note, code: code, type: type})
        end

        hash = {characteristics_questions: characteristics_questions}
        respond_with hash
      end

      def list
        index
      end

    end
  end
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < TravelerAwareController
  before_filter :get_traveler

  def update
  # Parameters: {"utf8"=>"✓", "authenticity_token"=>"4fozeJE2OD4XRerZcDD+P0gkjs5jdQA6tMz14zAD7pU=", "user_characteristics_proxy"=>{"disabled"=>"true", "ada_eligible"=>"na", "matp"=>"na", "veteran"=>"na", "date_of_birth"=>"", "folding_wheelchair_accessible"=>"na", "motorized_wheelchair_accessible"=>"na", "curb_to_curb"=>"na"}, "user_id"=>"28", "trip_id"=>"3", "id"=>"new"}
  # OR
  # {"user_answer"=>"true", "code"=>"ada_eligible", "user_id"=>"27"}

    input_values = normalize_input_values(params)

    @user_characteristics_proxy = UserCharacteristicsProxy.new(User.find(params[:user_id]))
    if @user_characteristics_proxy.update_maps(input_values)

      if params['inline'] == '1' || params[:trip_id]
        @trip = Trip.find(session[:current_trip_id] || params[:trip_id])
        if session[:is_multi_od] == true
          @multi_od_trip = MultiOriginDestTrip.find(session[:multi_od_trip_id] || params[:multi_od_trip_id])
          @path = user_trip_multi_od_grid_path(@traveler, @trip, @multi_od_trip)
        else
          @trip.remove_itineraries
          @path = populate_user_trip_path(@traveler, @trip, {asynch: 1}, locale: I18n.locale )
        end
      end

      # We assume the update is from the review page if it's ajax
      if request.xhr?
        render nothing: true, status: 200
        return
      end

      respond_to do |format|
        format.html { redirect_to @path}
        format.js { render "characteristics/update_form" }
      end
    else
      @trip_id = session[:current_trip_id] || params[:trip_id]
      @trip = Trip.find(@trip_id)
      @total_steps = (@traveler.has_disability? ? 3 : 2)
      render action: :new
    end

  end

  def normalize_input_values params
    return params[:user_characteristics_proxy] if params.include? :user_characteristics_proxy
    return { params[:code] => params[:user_answer] }
  end

  def new
    @user_characteristics_proxy = UserCharacteristicsProxy.new(@traveler)

    @trip_id = session[:current_trip_id] || params[:trip_id]
    @trip = Trip.find(@trip_id)
    @total_steps = (@traveler.has_disability? ? 3 : 2)

    respond_to do |format|
      format.html
    end
  end

  # TODO Not used anymore
  def header
    @total_steps = (params[:state] == 'user_characteristics_proxy_disabled_true' ? 3 : 2)
    Rails.logger.info  "total_steps: #{@total_steps}"

    respond_to do |format|
      format.html { render partial: 'header', locals: {total_steps: @total_steps}}
    end
  end
end

app/controllers/kiosk/characteristics_controller.rb
module Kiosk
  class CharacteristicsController < ::CharacteristicsController
    include Behavior

    def back_url
      kiosk_user_new_trip_overview_path
    end

    # below this copied from base controller, which is changing.
    before_filter :get_traveler

    def update
      @user_characteristics_proxy = UserCharacteristicsProxy.new(User.find(params[:user_id]))
      @user_characteristics_proxy.update_maps(params[:user_characteristics_proxy])

      if params['inline'] == '1'
        @path = new_user_program_path_for_ui_mode(@traveler, inline: 1)
      else
        @path = new_user_program_path_for_ui_mode(@traveler)
      end

      #if we are in the 'wizard' don't flash a notice. This logic checks to see if
      # the request was an ajax request or not. The trip-planning form does not
      # use ajax.
      if request.xhr?
        flash[:notice] = t(:profile_updated)
      end

      respond_to do |format|
        format.html { redirect_to @path }
        format.js { render "characteristics/update_form" }
      end
    end

    def new
      @user_characteristics_proxy = UserCharacteristicsProxy.new(@traveler)

      @trip_id = session[:current_trip_id]
      @trip = Trip.find(@trip_id)
      @total_steps = (@traveler.has_disability? ? 3 : 2)

      respond_to do |format|
        format.html
      end
    end

    def header
      @total_steps = (params[:state] == 'user_characteristics_proxy_disabled_true' ? 3 : 2)
      Rails.logger.info  "total_steps: #{@total_steps}"

      respond_to do |format|
        format.html { render partial: 'header', locals: {total_steps: @total_steps}}
      end
    end


  end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
  def active_button f, item, value
   f.object.send(item.code.to_sym) == value ? 'active' : ''
  end
end

app/views/characteristics/_characteristic_item.html.haml
- if is_arc?
  %table.col-sm-12
    %tbody
      %tr
        %td.characteristics-icon{:style => 'background-image: url(' + logo_path_from_view_helper(item) + ');'}
        %td{:style => 'width: 100%'}
          - case item.datatype
            - when 'bool'
              .form-group.string.optional
                .string.optional.col-sm-7.control-label{id: "#{item.code}_label", for: item.code}
                  = translate_helper_translate(item.note)
                  - if translation_exists?("#{item.code}_help")
                  - help_tag = "#{item.code}_help".to_sym
                    :javascript
                      addHelperTooltip("##{item.code}_label", "#{translate_helper_translate(help_tag)}");
                .col-sm-5
                  = f.input item.code.to_sym, id: item.code, :collection =>  [[translate_helper_translate(:yes_str), 'true'], [translate_helper_translate(:no_str), 'false'], [translate_helper_translate(:not_sure_str), UserProfileProxy::PARAM_NOT_SET]], :selected => item.selected_option(@traveler), input_html: { class: 'form-control', style: 'min-width:120px;' }, label: false
            - else
              = f.input item.code.to_sym, label: translate_helper_translate(item.note)
              - if translation_exists?("#{item.code}_help")
                :javascript
                  addHelperTooltip("##{item.code}_label", "#{translate_helper_translate(:date_of_birth_help)}");
- else
  - case item.datatype
    - when 'bool'
      %fieldset
        .form-group.radio_buttons.optional#input_container{class: "user_characteristics_proxy_#{item.code}"}
          %legend.col-sm-7.radio_buttons.optional.control-label{id: "#{item.code}_label"}
            = translate_helper_translate(item.note)
            = add_tooltip("#{item.code}_help")
            :javascript
              $('.inline-radio .label-help').removeClass('fa-2x');
          .col-sm-5#eligibility_questions
            %input.radio_buttons.optional{id: "user_characteristics_proxy_#{item.code}_true", name: "user_characteristics_proxy[#{item.code}]", type: "radio", value: "true", checked: item.true_false_checked?(@traveler, "true") }
            %label{for: "user_characteristics_proxy_#{item.code}_true", name: "user_characteristics_proxy[#{item.code}]"} #{translate_helper_translate(:yes_str)}

            %input.radio_buttons.optional{id: "user_characteristics_proxy_#{item.code}_false", name: "user_characteristics_proxy[#{item.code}]", type: "radio", value: "false", checked: item.true_false_checked?(@traveler, "false") }
            %label{for: "user_characteristics_proxy_#{item.code}_false", name: "user_characteristics_proxy[#{item.code}]"} #{translate_helper_translate(:no_str)}

            %input.radio_buttons.optional{id: "user_characteristics_proxy_#{item.code}_na", name: "user_characteristics_proxy[#{item.code}]", type: "radio", value: "na", checked: item.na_checked?(@traveler) }
            %label{for: "user_characteristics_proxy_#{item.code}_na", name: "user_characteristics_proxy[#{item.code}]"} #{translate_helper_translate(:not_sure_str)}

      / = f.input item.code.to_sym, collection: [[true, translate_helper_translate(:yes_str)], [false, translate_helper_translate(:no_str)], [UserProfileProxy::PARAM_NOT_SET, translate_helper_translate(:not_sure_str)]], :required => false, as: :radio_buttons, label: translate_helper_translate(item.note), label_method: :last, value_method: :first
    - else
      = f.input item.code.to_sym, label: translate_helper_translate(item.note)
      - if translation_exists?("#{item.code}_help")
        :javascript
          addHelperTooltip("##{item.code}_label", "#{translate_helper_translate(:date_of_birth_help)}");

app/views/characteristics/_eligibility_alert.html.haml
- if inline
  .alert.alert-info.alert-block
    .row
      .col-sm-12
        %p
          / In order to plan a trip with your needs in mind, would you please tell us about yourself?
          = translate_helper_translate(:plan_with_you_in_mind) + " " + translate_helper_translate(:to_see_best_options)
    .row
      .col-sm-12
        %a.btn.btn-success{:alt => 'alt words', :title => 'title here', :href => skip_user_trip_path(@traveler, @trip_id)}
          %i{class: "icon #{CsHelpers::ACTION_ICONS[:plan_a_trip]}"}
          / No thanks, just plan my trip
          = translate_helper_translate(:no_thanks_just_plan_it)

app/views/characteristics/_form.html.haml
- if is_arc?
  .row
    .col-xs-12
      = simple_form_for @user_characteristics_proxy, :url => new_user_trip_characteristic_path(@traveler, @trip, locale: I18n.locale), method: 'PUT', html: {class: 'user-characteristics form-horizontal'}, wrapper: :h_opts_form, wrapper_mappings: {check_boxes: :h_opts_radio_and_checkboxes, radio_buttons: :h_opts_radio_button_groups, file: :h_opts_file_input, boolean: :h_opts_boolean }  do |f|
        = f.error_notification message: print_messages(f)
        / %form{:role => "form"}
        .inline-radio
          -Characteristic.active.enabled.each do |c|
            - next unless c.for_traveler == true
            - next unless c.ask_early
            = render partial: 'characteristic_item', locals: {item: c, f: f}
          -Accommodation.where(:datatype => 'bool').each do |a|
            - next unless a.ask_early
            = render partial: 'characteristic_item', locals: {item: a, f:f}
          :javascript
            $('.user-characteristics .char-group').on('click',
              function(e) {
                $(e.currentTarget).find('.btn').removeClass('active');
                $(e.target).addClass('active');
                $(e.currentTarget).find('input').val($(e.target).val());
                //console.log($(e.target).val());
                //console.log($(e.currentTarget).find('input'));
              }
            );

- else
  .row
    .col-xs-12
      = simple_form_for @user_characteristics_proxy, :url => new_user_trip_characteristic_path(@traveler, @trip, locale: I18n.locale), method: 'PUT', html: {class: 'user-characteristics form-horizontal'}, wrapper: :h_opts_form, wrapper_mappings: {check_boxes: :h_opts_radio_and_checkboxes, radio_buttons: :h_opts_radio_and_checkboxes, file: :h_opts_file_input, boolean: :h_opts_boolean }  do |f|
        = f.error_notification message: print_messages(f)
        / %form{:role => "form"}
        .inline-radio
          -Characteristic.active.enabled.for_traveler.each do |c|
            - next unless c.for_traveler == true
            - next unless c.ask_early
            = render partial: 'characteristic_item', locals: {item: c, f: f}
          -Accommodation.where(:datatype => 'bool').each do |a|
            - next unless a.ask_early
            = render partial: 'characteristic_item', locals: {item: a, f:f}

app/views/characteristics/_header.html.haml
=translate_helper_translate(:about_you) +" - " + translate_helper_translate(:step_one_of) + " "
= total_steps

app/views/characteristics/new.html.haml
- content_for :title, "#{translate_helper_translate(:site_title)} - #{translate_helper_translate(:eligibility_accommodation_questions)}"
- is_splash_available = whether_show_tranlatation_item?(:options_page_splash)
- non_splash_css = 'col-sm-12'
- splash_css = ''
- if is_splash_available
  - non_splash_css = 'col-sm-7 col-xs-12'
  - splash_css = 'col-sm-5 col-xs-12'
.row
  %div{class: non_splash_css}
    .pull-right
      = button_tag :type => 'submit', :name => 'planTrip', :class => "btn action-button" do
        =translate_helper_translate(:next)
        :javascript
          $(function() {
            $('button[name=planTrip]').click(function() {
              $('.user-characteristics').submit();
            });
          });
    = render partial: 'shared/trip_plan_breadcrumbs'

.row
  %div{class: non_splash_css}
    .col-sm-12
      = render partial: 'shared/page_comments', locals: {key: :options_header_comment}
    .col-sm-12.panel.panel-default{:role => "main", :aria => {:label => 'Eligibility and Accommodation Form'}, :style => 'padding: 0px;'}
      .panel-heading
        %h2.panel-title
          =translate_helper_translate(:eligibility_accommodation_questions)
          = add_tooltip("eligibility_accommodation_questions_help")
      .panel-body
        = render partial: 'form', :locals => {:path => user_characteristic_path(@traveler, @user_characteristics_proxy.id, inline: 1), :inline => true}
        / end of options column
    .col-xs-12{style: "margin-bottom: 5px; padding: 0px;"}
      = button_tag :type => 'submit', :name => 'planTrip', :class => "btn pull-right action-button" do
        =translate_helper_translate(:next)
    .col-sm-12
      = render partial: 'shared/page_comments', locals: {key: :options_footer_comment}
  - if is_splash_available
    = render partial: 'shared/splash', locals: {splash_key: :options_page_splash, title_key: :options_page_splash_title, splash_div_class: splash_css}

app/views/characteristics/update_accommodations_form.js.haml
remove_messages();
// Show any new messages
$('#messages').html("#{escape_javascript(render 'shared/messages')}");

$('#accommodations_form').html("#{escape_javascript(render 'devise/registrations/accommodations')}");

app/views/characteristics/update_characteristics_form.js.haml
remove_messages();
// Show any new messages
$('#messages').html("#{escape_javascript(render 'shared/messages')}");

app/views/characteristics/update_form.js.haml
remove_messages();
$('#messages').html("#{escape_javascript(render 'shared/messages')}");